create table imagine_if_question
(
    id   bigserial    not null,
    question varchar not null,
    answer1 varchar(300) not null,
    answer2 varchar(300) not null,
    answer3 varchar(300) not null,
    answer4 varchar(300) not null,
    answer5 varchar(300) not null,
    answer6 varchar(300) not null,

    primary key (id)
);

create table imagine_if_game_round
(
  id                            bigserial    not null,
    game_room_id bigint not null references game_room(id),
    player_id bigint not null references player(id),
    round int not null,
    answer int,
    question_id bigint not null references imagine_if_question(id),
    selected_player_id integer default 1,
primary key (id)
);

insert into imagine_if_question (question, answer1, answer2, answer3, answer4, answer5, answer6) VALUES
('If [person] were a book, which would they be?', 'Unabridged Dictionary', 'Green Eggs and Ham', 'How to Win Friends and Influence People', 'Moby Dick', 'The Da Vinci Code', 'Chicken Soup for the Soul'),
('If [person] were a dog, which would they be?', 'Alaskan Husky', 'French Poodle', 'Rottweiler', 'Basset Hound', 'Golden Retriever', 'Mutt'),
('If [person] were a bad habit, which would they be?', 'Picking nose', 'Gossiping', 'Breaking wind in public', 'Biting nails', 'Road rage', 'Constantly looking in mirror'),
('If [person] were a type of footwear, which would they be?', 'Black wingtips', 'Stiletto heels', 'Nikes', 'Cowboy boots', 'Ballet slippers', 'Flip Flops'),
('If [person] were a type of confection, which would they be?', 'M & M’s', 'Gum', 'Cotton Candy', 'Breath Mint', 'Chocolate liqueur', 'Jelly Bean'),
('If [person] were a TV catchphrase, which would they be?', '“You’re fired”', '“Beam me up, Scotty”', '“Yada, yada, yada...”', '“BAM!”', '“Elvis has left the building”', '“Yabba dabba do!”'),
('If [person] were a part of a garden, which would they be?', 'Flowers', 'Weeds', 'Native trees', 'Manicures lawn', 'Concrete', 'Gnomes and fountains'),
('If [person] were a fictional crime fighter, which would they be?', 'Dirty Harry', 'Sheriff Andy Taylor', 'Austin Powers', 'Nancy Drew', 'James Bond', 'Part of the CSI team'),
('If [person] were a simile, which would they be?', 'Dumb as a stump', 'Hungry as a wolf', 'Sly as a fox', 'Proud as a peacock', 'Grouchy as a bear', 'Strong as an ox'),
('If [person] were a hairstyle, which would they be?', 'Perm', 'Ponytail', 'Mullet', 'Completely shaven', 'Extensions and highlights', 'Dreadlocks'),
('If [person] were a color, which would they be?', 'Khaki', 'Lavender ', 'Green', 'Chartreuse', 'Gold', 'Jet black'),
('If [person] were a thing to look through, which would they be?', 'Telescope', 'Sunglasses', 'Reading glasses', 'Binoculars ', 'Safety goggles ', 'Rose colored glasses'),
('If [person] were a fashion fad, which would they be?', 'Poodle skirt and saddle shoes', 'Leisure suit', 'Victorian corset and gown', 'Knickers', 'Jordache and jeans', 'Toga'),
('If [person] were a feature, which would they be?', 'Aretha Franklin’s voice', 'Kramer’s hair', 'Angelina Jolie’s lips', 'Einstein’s brain', 'Brad Pitts body', 'Sean Connery’s accent'),
('If [person] were a breakfast, which would they be?', 'Cocoa Puffs', 'Steak and eggs ', 'Coffee and more coffee', 'Fruit and yogurt', 'Pancakes with maple syrup ', 'Brunch and mimosas'),
('If [person] were a member of the seven dwarfs, which would they be?', 'Sleepy', 'Sneezy', 'Dopey', 'Grumpy', 'Bashful', 'Doc'),
('If [person] were a movie catchphrase, which would they be?', '“Here’s looking at you, kid”', '“Go ahead, make my day”', '“May the force be with you”', '“Vodka martini, shaken, not stirred”', '“There’s no place like home”', '“This is another fine mess you’ve gotten me into”'),
('If [person] were a phobia, which would they be?', 'Ochlophobia (fear of crowds)', 'Arachnophobia (fear of spiders)', 'Triskaidekaphobia (fear of thirteen)', 'Mysophobia (fear of dirt)', 'Acrophobia (fear of heights)', 'Nyctophonia (fear of darkness)'),
('If [person] were a soup, which would they be?', 'Split pea', 'French onion', 'Won ton', 'Gazpacho', 'Chicken Noodle', 'Clam Chowder'),
('If [person] were a female name, which would they be?', 'Jane', 'Brittany', 'Victoria', 'Olga', 'Sybil ', 'Summer'),
('If [person] were a TV family, which would they be?', 'The Waltons', 'The Osbornes', 'The Simpsons', 'The Sopranos', 'The Partridge Family', 'The Dukes of Hazzard'),
('If [person] were a Beatle, which would they be?', 'John', 'Paul', 'George', 'Ringo', 'Volkswagen', 'Dung'),
('If [person] were a famous author, which would they be?', 'John Grisham', 'Mark Twain', 'Dale Carnegie', 'Stephen King', 'Dr. Seuss', 'J. K. Rowling'),
('If [person] were a 1970s movie, which would they be?', 'Love Story ', 'Star Wars', 'Jaws', 'The Godfather', 'Kramer vs. Kramer', 'Saturday Night Fever'),
('If [person] were a musical style, which would they be?', 'Country and Western', 'Hip Hop', 'Blues', 'Smooth jazz', 'Punk', 'Opera'),
('If [person] were a TV channel, which would they be?', 'NFL Network', 'MTV', 'Lifetime', 'Food Network', 'Cartoon Network', 'C-SPAN'),
('If [person] were a wheel, which would they be?', 'Big wheel', 'Squeaky wheel', 'Free wheel', 'Hamster wheel', 'Wheel of Fortune', '5th wheel'),
('If [person] were a dance, which would they be?', 'Ballroom', 'Line', 'Interpretive', 'Salsa', 'Riverdance', 'Hokey Pokey'),
('If [person] were a clichè, which would they be?', 'Wolf in sheep’s clothing', 'Born with a silver spoon in the mouth', 'Burning the candle at both ends', 'At one with nature', 'Look what the cat dragged in', 'A sight for sore eyes'),
('If [person] were a thing worn on the hand, which would they be?', 'Brass knuckles ', 'Silk glove', 'Diamond ring', 'Rubber glove', 'Puppet', 'Mitten'),
('If [person] were a 1960’s movie, which would they be?', 'Barbarella', 'The Sound of Music', '2001 - A Space Odyssey', 'Goldfinger', 'Psycho ', 'Dr. Zhivago'),
('If [person] were a member of a threesome, which would they be?', '3 Stooges', '3 Tenors', '3 Musketeers', '3 Wise Men', '3 Blind Mice', '3 Mile Island'),
('If [person] were a 1980’s movie, which would they be?', 'Terminator', 'Fatal Attraction', 'Amadeus', 'Ferris Bueller’s Day Off', 'E. T. ', 'On Golden Pond'),
('If [person] were a pain or ailment, which would they be?', 'Headache', 'Stomach ache', 'Stiffness', 'Leg cramp', 'Hot flashes', 'Pain in the rear'),
('If [person] were a plant, which would they be?', 'Four leaf clover', 'Bird of paradise', 'Towering oak', 'Spiny cactus', 'Hardy ‘Mum', 'Shrub'),
('If [person] were a musical instrument, which would they be?', 'Piano', 'Drums', 'Banjo', 'Electric guitar', 'Cowbell', 'Accordion'),
('If [person] were a Holiday, which would they be?', 'Labor Day', 'Thanksgiving', 'Mardi Gras', 'Sweetest Day', 'April Fool’s Day', 'Halloween'),
('If [person] were a position on a football team., which would they be?', 'Tight end', 'Split end', 'Safety', 'Special teams player', 'Punter', 'Quarterback'),
('If [person] were an era, which would they be?', 'Biblical era', 'Computer age', 'Old west', 'Decadent Rome', 'Stone Age', 'Victorian Era'),
('If [person] were a special vehicle. Which would he/she be?, which would they be?', 'Tank', 'Ambulance', 'Parade Float', 'Garbage truck', 'Ice cream truck', 'Limousine'),
('If [person] were an entrèe, which would they be?', 'Meatloaf', 'Lobster Thermadore', 'Mixed green salad', 'Sushi', 'Dry toast', 'Big Mac'),
('If [person] were a weather forecast, which would they be?', 'Hot and humid', 'Tornado warning', 'Light drizzle and fog', 'High pressure ', 'Sunny and mild', 'Cold front'),
('If [person] were a font, which would they be?', 'The Hard Way', 'Times New Roman', 'Dead History', 'Passions Conflict', 'Megahertz', 'Grunge'),
('If [person] were a kitchen utensil, which would they be?', 'Rolling pin', 'Cheese grater', 'Oven mitt', 'Corkscrew', 'Nutcracker', 'Whisk'),
('If [person] were a sea creature, which would they be?', 'Hammerhead shark', 'Dolphin', 'Octopus', 'Angel fish', 'Jellyfish', 'Crab'),
('If [person] were a profession, which would they be?', 'Astronaut', 'Photographer', 'Lawyer', 'Chef', 'Model', 'Brick layer'),
('If [person] were a car, which would they be?', 'MINI Cooper', 'Minivan', 'Hybrid', 'Hummer', 'Jaguar', 'Taxicar'),
('If [person] were a sportsman, which would they be?', 'Tiger Woods', 'Tony Hawk', 'Johnny Unitas', 'Muhammad Ali', 'Terrell Owens', 'Tom Brady'),
('If [person] were a song at a karaoke bar, which would they be?', '“I Love Rock and Roll”', '“New York, New York”', '“I Will Survive”', '“Figaro”', '“Oops, I did it again”', '“Friends in Low Places”'),
('If [person] were a product sold on t.v., which would they be?', 'Thighmadter', 'George Foreman Grill', 'Richard Simmons’ Sweatin to the Oldies', 'Craftmatic Adjustable Bed', 'Anne Murray’s Greatest Hits', 'Ron Popeil’s GLH spray on hair.'),
('If [person] were a piece of jewelry, which would they be?', 'Wedding ring', 'Inspirational bracelet', 'Jeweled crown', 'Rolex', 'Cubic zirconia', 'Tongue piercing'),
('If [person] were a person in a courtroom, which would they be?', 'Bailiff', 'Judge', 'Stenographer', 'Defendant', 'District Attorney', 'Court TV Reporter'),
('If [person] were a type of headgear, which would they be?', 'Baseball cap', 'Top hat', 'Beret', 'Toupee', 'Miner’s helmet', 'Virtual reality goggles'),
('If [person] were a punctuation mark, which would they be?', 'Question mark', 'Number sign', 'Quotation marks', 'Parentheses', 'Exclamation point', 'Colon'),
('If [person] were a part of a computer, which would they be?', 'Monitor', 'Microprocessor', 'Graphics card', 'Floppy Disk', 'Networking card', '<ESC>ape key'),
('If [person] were a motto, which would they be?', 'Pedal to the metal', 'Stop and smell the roses', 'Take the road less traveled', 'Better safe than sorry', 'An eye for an eye, a tooth for a tooth', 'Love makes the world go round'),
('If [person] were a cartoon character, which would they be?', 'Goofy', 'Shaggy', 'Cinderella', 'Tasmanian Devil', 'Wilma Flintstone', 'Mr. Magoo'),
('If [person] were a political quote, which would they be?', '“I do not like broccoli” (Bush)', '“I am not worried about the deficit - it is big enough to take care of itself” (Reagan)', '“Speak softly and carry a big stick” (T. Roosevelt)', '“I had a lot of experience with people smarter than I am” (Ford)', '“Be sincere, be brief, be seated” (FDR)', '“The buck stops here” (Truman)'),
('If [person] were a piece of advise, which would they be?', 'Trust no one', 'Be honest at all times', 'Never walk under a ladder', 'Dress for success', 'Marry a millionaire', 'Eat all your vegetables'),
('If [person] were a timepiece, which would they be?', 'Stopwatch', 'Biological clock', 'Grandfather clock', 'Oven timer', 'Sundial', 'Time bomb'),
('If [person] were a 1950’s movie, which would they be?', 'The Ten Commandments', 'Gentlemen Prefer Blondes', 'Father of the Bride', 'The Wild One', 'The Greatest Show on Earth', 'Around the World in 80 Days'),
('If [person] were a U.S. President, which would they be?', 'George Washington', 'Ronald Reagan', 'Teddy Roosevelt', 'Richard Nixon', 'John F. Kennedy', 'George W. Bush'),
('If [person] were a World Record, which would they be?', 'Shortest attention span', 'Most slippery surface', 'Loudest burp', 'Longest phone call', 'Fastest six digit square root calculation ', 'Wettest spot on Earth'),
('If [person] were a spots penalty, which would they be?', 'Holding', 'Delay of game', 'Head butting ', 'Too many men', 'False start', 'Excessive celebration'),
('If [person] were a form of communication, which would they be?', 'Telephone', 'Mental telepathy', 'Body language', 'Email', 'Car horn', 'Smoke signal'),
('If [person] were a sport, which would they be?', 'Baseball', 'Surfing ', 'Stock car racing', 'Duplicate bridge', 'Take Kwon do', 'Big Air Skateboarding'),
('If [person] were a feeling, which would they be?', 'Angry', 'Tired ', 'Cheerful', 'Stressed', 'Romantic', 'Bored'),
('If [person] were a chorus of a song, which would they be?', '“Sing us a song, you’re the piano man”', '“I’m proud to be an American, where at least I know I’m free”', '“I heard it through the grapevine” ', '“Thank you for being a friend”', '“You ain’t nothing but a hound dog”', '“It’s fun to stay at the YMCA”'),
('If [person] were a subject of a photograph, which would they be?', 'Seated, formally dressed', 'Police mug shot', 'Out of focus', 'Making a funny face', 'Action shot', 'Cover of The Enquirer'),
('If [person] were a sense, which would they be?', 'Touch', 'Sight', 'Smell', 'Hearing', 'Taste', 'E. S. P.'),
('If [person] were a dessert, which would they be?', 'Triple Chocolate Tart', 'Apple pie', 'Crème Brulèe', 'Fresh fruit', 'Port and cigars', 'Cookies and milk'),
('If [person] were a light source, which would they be?', 'Candle', 'Sun', 'Lightening', 'Flashlight', 'Lava Lamp', 'Laser beam'),
('If [person] were a part of a car, which would they be?', 'Seat belt', 'Sunroof', 'Gas pedal', 'Horn', 'Spare tire', 'Navigation system'),
('If [person] were a stage act, which would they be?', 'Poetry reading', 'Stand up comedy', 'One man band', 'Magic act', 'Snake charming', 'Belly dancing'),
('If [person] were a 1990’s movie, which would they be?', 'Independence Day', 'Pulp Fiction', 'The English Patient', 'Forrest Gump', 'Pretty Woman', 'There’s Something About Mary'),
('If [person] were a Peanut’s character, which would they be?', 'Charlie Brown', 'Snoopy', 'Lucy', 'Linus', 'Pig Pen', 'Schroeder'),
('If [person] were a writing instrument, which would they be?', 'Fountain pen', 'Keyboard', 'Chalk', 'Ball point pen', 'Crayon', 'Spray paint'),
('If [person] were an animal, which would they be?', 'Sheep Dog', 'Chimpanzee', 'Koala Bear', 'Bull', 'Panther', 'Toad'),
('If [person] were an article of clothing, which would they be?', 'Tailored suit', 'Jeans', 'Sports Jersey', 'Bathrobe', 'Carhartts', 'Thong'),
('If [person] were an expert testimony at a trial, which would they be?', 'Marriage counselor', 'Environmental expert', 'Handwriting analyst', 'Paranormal psychic', 'Pet Behavior specialist', 'Gastrointestinal surgeon'),
('If [person] were an emotion, which would they be?', 'Rage', 'Glee', 'Paranoia ', 'Apathy', 'Desire', 'Smugness'),
('If [person] were an item found in a vending machine, which would they be?', 'Cheetos', 'Animal crackers', 'Good & Plenty', 'Granola bar', 'Goobers', 'The one that’s still stuck'),
('If [person] were a collection, which would they be?', 'Trading cards', 'Speeding tickets', 'Phone numbers', 'Live insects', 'Dust bunnies', 'Fabergè Eggs'),
('If [person] were a body part, which would they be?', 'Face', 'Buttocks', 'Stomach', 'Hand', 'Brain', 'Mouth'),
('If [person] were a floor covering, which would they be?', 'Hardwood floor', 'Shag carpet', 'Marble tile', 'Bearskin rug', 'Rubber floor mat', 'Concrete'),
('If [person] were a card game, which would they be?', 'War', 'Crazy 8’s ', 'Solitaire', 'Rummy', 'Texas Hold ‘Em Poker', 'Old Maid'),
('If [person] were a magazine, which would they be?', 'Martha Stewart Living', 'People', 'Sports Illustrated', 'Popular Science', 'Fortune', 'Cosmopolitan'),
('If [person] were a circus performer, which would they be?', 'Clown', 'Trapeze artist', 'Lion tamer', 'Juggler', 'Fire eater', 'Performing poodle'),
('If [person] were a tool, which would they be?', 'Sledge hammer', 'Pruning shears', 'Screwdriver', 'Level', 'Cocktail mixer', 'Toenail clippers'),
('If [person] were a display of friendship, which would they be?', 'Kiss', 'Hug', 'Firm Handshake', 'Wink', 'High five', 'Slap on the back'),
('If [person] were a mode of transportation, which would they be?', 'Hot rod', 'Pogo stick', 'Horse and buggy', 'Time machine', 'Corporate jet', 'Jogging'),
('If [person] were a war or battle, which would they be?', 'Star Wars', 'Battle of Wits', 'Civil War', 'Battle of Bands', 'Hundred Years War', 'Battle of the Bulge'),
('If [person] were a parcel, which would they be?', 'First class', 'Bulk rate', 'Overnight', 'This side up', 'Standard ground', 'Fragile- handle with care'),
('If [person] were a sad person and needed a laugh. Who could provide it?, which would they be?', 'Will Ferrell', 'Chris Rock', 'Lucille Ball', 'Abbott and Costello', 'Monty Python', 'George W. Bush'),
('If [person] were a type of document, which would they be?', 'Pre-nuptial agreement', 'Parent papers', 'I.O.U.', 'Balance sheet', 'Instructions', 'Warrant'),
('If [person] were a flying object, which would they be?', 'Blimp', 'Biplane', 'Glider', 'Frisbee', 'Learjet', 'Brick'),
('If [person] were a donut, which would they be?', 'Boston cream', 'Plain', 'French curler', 'Peanut stick', 'Munchkin', 'Apple Fritter'),
('If [person] were a store manager, which would they be?', '7-Eleven', 'Home Depot', 'Starbucks', 'Petsmart', 'Tiffany''s', 'Sunglass Hut'),
('If [person] were a surgical operation, which would they be?', 'Hip replacement', 'Wart removal', 'Nose job', 'Knee reconstruction', 'Bloodletting', 'Laser hair removal'),
('If [person] were a famous landmark, which would they be?', 'Empire State Building', 'Taj Mahal', 'The "Hollywood" sign', 'Leaning Tower of Pisa', 'Yankee Stadium', 'The Sphinx'),
('If [person] were a room, which would they be?', 'Study', 'Kitchen', 'Wine cellar', 'Bedroom', 'Bathroom', 'Darkroom'),
('If [person] were a form of advertisement, which would they be?', 'Internet pop-up ad', 'Bumper sticker', 'Classified ad', 'Infomercial', 'Full page magazine ad', 'Subliminal advertising'),
('If [person] were a musician, which would they be?', 'Ella Fitzgerald', 'Bono', 'Barbra Streisand', 'Britney Spears', 'Lawrence Welk', 'The artist formerly known as, and now again as, Prince'),
('If [person] were a condiment, which would they be?', 'Salt', 'Maple syrup', 'Steak Sauce', 'Extra virgin olive oil', 'Tabbasco sauce', 'Vinegar'),
('If [person] were a high school class, which would they be?', 'Social Studies', 'Home Economics', 'Trigonometry', 'Lunch', 'Gym', 'Study Hall'),
('If [person] were a bird, which would they be?', 'Bald Eagle', 'Hummingbird', 'Road Runner', 'Albatross', 'Whooping Crane', 'Prairie Chicken'),
('If [person] were a toy, which would they be?', 'Easy-Bake Oven', 'Yo-yo', 'Chemistry set', 'Barbie Doll', 'Teddy bear', 'Play-Doh'),
('If [person] were a gift, which would they be?', 'Box of chocolates', 'Savings bond', 'A new Mercedes', 'Slippers', 'Gift certificate', 'Aqua Velva'),
('If [person] were a board game, which would they be?', 'Monopoly', 'Scrabble', 'Twister', 'iMagiNiff', 'Chess', 'Candy Land'),
('If [person] were a power source, which would they be?', 'Wind', 'Solar', 'Steam', '9 volt battery', 'Coal', 'Nuclear'),
('If [person] were a crime, which would they be?', 'Disorderly conduct', 'Tax evasion', 'Littering', 'Illegal use of motor vehicle', 'Removal of mattress tags', 'Computer hacking'),
('If [person] were a product mascot, which would they be?', 'Jolly Green Giant', 'Cap''n Crunch', 'Chiquita Banana lady', 'Mrs. Butterworth', 'Pillsbury Doughboy', 'Grimace'),
('If [person] were a piece of sporting equipment, which would they be?', 'Horseshoe', 'Baseball mitt', 'Putter', 'Foul pole', 'Trampoline', 'Jockstrap'),
('If [person] were a piece of furniture, which would they be?', 'Recliner', 'Picnic table', 'Vanity', 'Italian leather sofa', 'Desk', 'Milk crate'),
('If [person] were a criminal, which would they be?', 'Al Capone', 'Richard Nixon', 'Martha Stewart', 'The Joker', 'Robin Hood', 'Lex Luthor'),
('If [person] were a city, which would they be?', 'Hollywood', 'Bismarck', 'Paris', 'Rio de Janeiro', 'Springfield', 'Atlantis'),
('If [person] were a dental procedure, which would they be?', 'Cosmetic whitening', 'Regular check-up', 'Gold tooth', 'Root canal', 'Braces', 'Dentures'),
('If [person] were a home, which would they be?', 'Four bedroom ranch', 'Penthouse apartment', 'Mobile home', 'Tree house', 'Southern plantation', 'Beach house'),
('If [person] were a street sign, which would they be?', 'STOP', 'Neighborhood Watch', '75 MPH', 'Scenic Overlook', 'Dangerous Curves Ahead', 'Bridge Out'),
('If [person] were a piece of luggage, which would they be?', 'Carry-on', 'Steamer trunk', 'Pet carrier', 'Laptop case', 'Plastic grocery bag', 'Golf travel bag'),
('If [person] were a weapon, which would they be?', 'Poison', 'Squirt gun', 'Light saber', 'Battle Axe', 'Charm', 'Pepper Spray'),
('If [person] were a time measurement, which would they be?', 'Season', 'Era', 'Nanosecond', 'Fiscal year', 'Happy hour', 'Overtime'),
('If [person] were a floating vessel, which would they be?', 'Gondola', 'Destroyer', 'Speedboat', 'Kayak', 'Luxury liner', 'Fishing trawler'),
('If [person] enjoyed a day in the snow, which would he/she do?', 'Go ice fishing', 'Take extreme jumps at the terrain park', 'Head for the lodge bar', 'Meander down a forest trail', 'Make snow angels', 'Spin "donuts" in a parking lot'),
('If [person] were an item in the refrigerator, which would they be?', 'Gallon of Milk', 'Crown of Broccoli', 'Baking soda', 'Leftover Moo Goo Gai Pan', 'Caviar', 'Prune juice'),
('If [person] were an insect, which would they be?', 'Louse', 'Ant', 'Wasp', 'Cicada', 'Praying Mantis', 'Firefly'),
('If [person] were an item found in a basement, which would they be?', 'High school yearbook', 'Dusty weight bench', 'Blown fuse', 'Cobweb', 'Drum set', '1954 Chateau Lafite Rothschild'),
('If [person] were an Olympic Event, which would they be?', 'Beach volleyball', 'Figure skating', 'Wrestling', 'Ping-pong', '100 meter dash', 'Shot put'),
('If [person] were awakened at night by a burglar, which would they be?', 'Go back to sleep and rely on the insurance', 'Scream', 'Wake his/her partner and demand action', 'Tackle the burglar to the ground', 'Sneak out and phone the police', 'Attempt to counsel the burglar'),
('If [person] were something to sit on, which would they be?', 'Throne', 'Bleachers', 'Lap', 'Lawn chair', 'Sit ''n Spin', 'Bar stool'),
('If [person] were on a reality TV show, which would they be?', 'The Apprentice', 'American Idol', 'People''s Court', 'American Chopper', 'Trading Spaces', 'The Amazing Race'),
('If [person] could keep only one of the following, which would they be?', 'Television', 'Books', 'Computer', 'Telephone', 'Blow dryer', 'Wine collection'),
('If [person] could play in a band, which would they be?', 'Tommy Dorsey Orchestra', 'Dixie Chicks', 'Led Zeppelin', 'Bee Gees', 'Josie and the Pussycats', 'US Marine Corps Band'),
('If [person] could be brilliant at one of the following, which would they be?', 'Golf', 'Painting', 'Gambling', 'Video games', 'Cooking', 'Programming cell phone'),
('If [person] were at a construction site, which would they be?', 'Barking out orders', 'Taking a coffee break', 'Doing something with a jackhammer', 'Drawing up the plans', 'Complaining about working conditions', 'Whistling at passerby'),
('If [person] stepped onto. a bus and the only other passenger was his/her favorite TV star, what would he/she do?', 'Ignore the star', 'Politely say "Hello" but respect their privacy', 'Tell the star about a great creative idea', 'Offer a critique of the star''s work', 'Nervously ask for an autograph', 'Drop their jaw and scream, "I love you!"'),
('If [person] could have a superpower, which would they choose?', 'Ability to fly', 'Superhuman strength', 'Mind control', 'Ability to talk to animals', 'Shape-shifting', 'X-ray vision'),
('If [person] personality were a male name, which would be best?', 'Melvin', 'Gunther', 'Earl', 'Rico', 'Chad', 'Jaques'),
('If [person] could acquire one of the following natural abilities, which would they choose?', 'Amazing hand-eye coordination', 'The ability to contact the spirit world', 'Photographic memory', 'The ability to win friends and influence people', 'Musical virtuosity', 'Optimism'),
('If [person] were traveling in space, how would they feel?', 'Proud', 'Nauseous', 'Terrified', 'Bored', 'Exhilarated', 'Weightless'),
('If [person] had the deciding vote for an Oscar for the greatest ever male actor, who would they choose?', 'Cary Grant', 'Ton Hanks', 'Clint Eastwood', 'Jackie Chan', 'Johnny Depp', 'Adam Sandler'),
('If [person] had to do one of the following, which would they fear the most?', 'Bungee jumping', 'Addressing the U.N. General Assembly', 'Catching a tarantula', 'Asking a secret crush on a date', 'Dining with the in-laws', 'Becoming a parent'),
('If [person] were hosting a party, how would they handle the food?', 'Have it professionally catered', 'Make everyone bring a dish', 'Put out a single tray of cocktail wieners', 'Spend 3 days preparing a 5 course meal', 'Have pizza and Buffalo wings delivered', 'Pretend to be suck at the last second and cancel the party'),
('If [person] could afford to buy a dream home, which would they buy?', 'Sprawling farmhouse', 'Beach condominium', 'Efficient eco-friendly home', 'Grand mansion', 'Rugged mountain lodge', 'Medieval castle'),
('If [person] were honked at by an impatient driver, how would they react?', 'Get out of the car and threaten the driver', 'Ignore it and turn up the radio', 'Honk ''em right back', 'Give a genuine apologetic wave', 'Record the license plate and call the police', 'Wink and lick the window'),
('If [person] could invite a famous historical figure home for dinner, whom would they invite?', 'Mother Teresa', 'Groucho Marx', 'John F. Kennedy', 'Henry Ford', 'Cleopatra', 'Muhammad Alo'),
('If [person] had made a million dollars, how would they have mostly likely made it?', 'Sporting prowess', 'Brilliant invention', 'Sheer hard work', 'Class action lawsuit', 'Winning the lottery', 'Show business'),
('If [person] awoke to find the house in flames, which would they save first?', 'Insurance policy', 'Favorite shoes', 'Family photos', 'Cash', 'Self portrait', 'Sports equipment'),
('If [person] inherited $100,000, what would they do?', 'Put an addition on the house', 'Blow it all at the mall', 'Donate it to charity', 'Invest it wisely', 'Head to Vegas', 'Bury it in the backyard'),
('If [person] could attend any sporting event, which would they choose?', 'World Figure Skating Championship', 'Daytona 500', 'The Masters', 'World Series', 'X Games', 'National Spelling Bee'),
('If [person] had to grant government approval for a major city project, which would they choose?', 'Hospital', 'Library', 'Casino', 'Sports stadium', 'Botanical gardens', 'Skyscraper'),
('If [person] were buying a home, which of the following would they consider most important?', 'School district', 'Big closets', 'Lush garden', 'Garbage and workshop', 'Distance from in-laws', 'Size of the kitchen'),
('If [person] were to be honored, which of the following would they be happiest to accept?', 'Employee of the Month', 'Parent of the Year', 'Cash Award', 'Blackwell''s Best Dressed List', 'Being knighted', 'Simple thank you note'),
('If [person] were choosing hotel accommodations, which of the following would they deem most important?', 'A big pool', 'Four star rating', 'Free breakfast', 'Workout facilities', 'Vibrating bed', 'Well stocked mini bar'),
('If [person] accidentally backed over the neighbor''s cat in the driveway, which would they do?', 'Bury it and say nothing', 'Confess', 'Buy a replacement and pretend nothing happened', 'Place it on the road and say nothing', 'Blame the neighbor for inadequate cat control', 'Run over it again to make sure it was dead'),
('If [person] were kissing goodnight after a first date, where would they plant it?', 'Lips', 'Back of hand', 'Cheek', 'Feet', 'Ear lobe', 'Tonsils'),
('If [person] could travel in a time machine, which event would they choose to witness?', 'Super Bowl III', 'Wright Brothers'' first flight', 'The first Thanksgiving', 'Their own birth', 'Next year''s Kentucky Derby', 'Woodstock'),
('If [person] could go on a dream vacation, which would it be?', 'Alaskan wilderness hike', 'Cultural tour of Europe', 'African safari', 'Week at Disney World', 'Hawaiian Islands trip', 'Relaxing and working at home'),
('If [person] spent a relaxing day alone, what would they do?', 'Go shopping', 'Surf the net', 'Watch TV', 'Meditate', 'Enjoy the great outdoors', 'Work on the tan'),
('If [person] could have dinner with an Olympic Champion, who would they choose?', 'Brian Boitano', 'Jesse Owens', 'Mary Lou Reton', 'Cassius Clay', 'Greg Louganis', 'Bruce Jenner'),
('If [person] witnessed a purse-snatching on the city street, what would they do?', 'Wrestle the purse-snatcher to the ground', 'Ignore it and keep walking', 'Attempt a citizen''s arrest', 'Offer counseling', 'Scream hysterically', 'Move to the country'),
('If [person] had to bay-sit a relative''s 5 year old kid, what would they do?', 'Take the kid to the zoo', 'Bake a tray of cookies', 'Eat junk food together and watch TV', 'Put the kid to work doing laundry and dishes', 'Teach the kid how to rebuild engines', 'Immediately hire a different babysitter'),
('If [person] could discover the answer to a great mystery, which mystery would they solve?', 'What is SPAM?', 'Where do the missing socks go?', 'Sasquatch- fact or fiction?', 'What goes on at Area 51?', 'Why was Stonehenge built?', 'How come I pay more taxes than Bill Gates?'),
('If [person] bought a newspaper, which would they read first?', 'Personals', 'Financial section', 'Sports', 'Comics', 'Obituaries', 'Want ads'),
('If [person] accidentally emitted an unpleasant anti-social noise at a dinner party, what would they do?', 'Say nothing and blush', 'Apologize', 'Laugh and repeat the offense (louder if possible)', 'Blame the person sitting next to them', 'Try to reproduce the sound by shifting in their seat', 'Carry on as if nothing happened'),
('If [person] could do only one of the following every morning, which would they choose?', 'Go for a 5 mile run', 'Sleep until 1:00pm', 'Drink coffee and read a newspaper', 'Spend quality time with spouse', 'Watch pre-game football shows', 'Take a 30 minute hot shower'),
('If [person] could watch only one of the following TV shows, which would it be?', 'World News Tonight', 'CSI', 'Desperate Housewives', 'Dora the Explorer', 'Sportscenter', 'Oprah'),
('If [person] won an overseas trip, which country would they visit?', 'Italy', 'Tibet', 'Iceland', 'Kenya', 'Tahiti', 'Monte Carlo'),
('If [person] were going on a first date, what would be the plan?', 'Dinner at a fancy restaurant and the symphony', 'Hot dogs, drinks, and a ball game', 'Stay in, order Chinese food and rent Sleepless in Seattle', 'Miniature golf and the mall food court', 'Moonlit horseback ride down the beach', 'Bail after 10 minutes'),
('If [person] found a piece of hair in their entree, what would they do?', 'Remove the hair and keep eating', 'Finish the meal, but refuse to pay for the entree', 'Storm out of the restaurant after giving the manager a tongue-lashing', 'Simply set the meal aside and say they are not hungry', 'Throw up', 'Ask for a replacement entree'),
('If [person] doctor suggested more exercise, which would they do?', 'Roller blade', 'Yoga', 'Triathlon', 'Mall walk', 'Tae Bo', 'Seek a second opinion'),
('If [person] could have just one pet, which would it be?', 'Goldfish', 'House cat', 'Boa constrictor', 'Pot-bellied pig', 'Shih Tzu', 'Peeve'),
('If [person] could enjoy one of life''s little luxuries every day. Which would they choose?', 'Long massage', 'Breakfast in bed', 'Fine scotch and cigar', 'A nap', 'Bubble bath', 'A maid'),
('If [person] had the deciding vote for an Oscar for the best actress, whom would they choose?', 'Julia Roberts', 'Lauren Bacall', 'Hilary Duff', 'Oprah Winfrey', 'Goldie Hawn', 'Paris Hilton'),
('If [person] had to decide the best way to spend New Year''s Eve, which would they choose?', 'A quiet celebration with the family', 'In the middle of Times Square', 'Attend the ballet and then a cocktail party', 'In deep meditation pandering the upcoming year', '48 straight hours of partying', 'Exactly the same as every other day'),
('If [person] were going on a picnic, which would they consider essential?', 'Sandwiched and coffee', 'Champagne and caviar', 'Laptop and cell phone', 'Loud radio', 'A bat and ball', 'A good book'),
('If [person] were on a 10 hour car trip, which would upset them the most?', 'Being stuck behind a little old lady traveling at 30 mph', 'Running over a bunny rabit', 'Children fighting in the back seat', 'A small scratch on the paint work', 'Sound system breaking down', 'Cell phone going out of range'),
('If [person] suffered a minor crisis, which would upset them the most?', 'Burning the roast', 'Scratch on the car', 'Computer virus', ' TV breaking down', 'Credit cards canceled', 'Stain on the lapel'),
('If [person] had to watch all of these movies, which would they dread the most?', 'Scream', 'The Matrix', 'Titanic', 'Lord of the Rings', 'Monty Python and the Holy Grail', 'The Sound of Music'),
('If [person] were an article of memorabilia, which would they be?', 'Jimi Hendrix guitar', 'Davy Crockett’s musket ', 'Neil Armstrong’s spacesuit', 'Van Gogh’s paintbrush', 'Jackie Onassis’ sunglasses ', 'William Shatner’s kidney stone'),
('If [person] were an animal sound, which would they be?', 'Meow', 'Moo', 'Roar', 'Gobble', 'Hiss', 'Hoot'),
('If [person] were an award, which would they be?', 'Academy Award', 'Nobel Prize', 'Most Valuable Player', 'Best in Show', 'Grammy', '4 Star Government Safety Rating'),
('If [person] were an invention, which would they be?', 'Lipstick', 'Microphone', 'Spork', 'Band-aid ', 'Blender', 'Sliced Bread');
